local Editor = include("editor/editor.lua")

concommand.Add("holo", function()
    Editor:Create()
    local prop1 = Editor:AddProp("models/holograms/cube.mdl")
    local prop2 = Editor:AddProp("models/holograms/sphere.mdl")
    local prop3 = Editor:AddProp("models/holograms/cube.mdl")
    local prop4 = Editor:AddProp("models/holograms/cube.mdl")
    Editor:RemoveProp(prop3)
end)