include("includes/modules/holoeditor.lua") --reload
require("HoloEditor")
HoloEditor:Init()
concommand.Add("holo", function()
    HoloEditor:Open()
    local prop1 = HoloEditor:AddProp("models/holograms/cube.mdl")
    local prop2 = HoloEditor:AddProp("models/holograms/sphere.mdl")
    local prop3 = HoloEditor:AddProp("models/holograms/cube.mdl")
    local prop4 = HoloEditor:AddProp("models/holograms/cube.mdl")
    HoloEditor:RemoveProp(prop3)
end)